/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Advertise`; params?: Router.UnknownInputParams; } | { pathname: `/AutoDetection`; params?: Router.UnknownInputParams; } | { pathname: `/FileDetection`; params?: Router.UnknownInputParams; } | { pathname: `/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/LinkDetection`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/Menu`; params?: Router.UnknownInputParams; } | { pathname: `/Notification`; params?: Router.UnknownInputParams; } | { pathname: `/Play`; params?: Router.UnknownInputParams; } | { pathname: `/Premuim`; params?: Router.UnknownInputParams; } | { pathname: `/Signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Account/forgetpassword`; params?: Router.UnknownInputParams; } | { pathname: `/Account/Login`; params?: Router.UnknownInputParams; } | { pathname: `/Account/request`; params?: Router.UnknownInputParams; } | { pathname: `/Account/Signup`; params?: Router.UnknownInputParams; } | { pathname: `/Account/User`; params?: Router.UnknownInputParams; } | { pathname: `/UserStorage/profilePic`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Advertise`; params?: Router.UnknownOutputParams; } | { pathname: `/AutoDetection`; params?: Router.UnknownOutputParams; } | { pathname: `/FileDetection`; params?: Router.UnknownOutputParams; } | { pathname: `/ForgotPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/LinkDetection`; params?: Router.UnknownOutputParams; } | { pathname: `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/Menu`; params?: Router.UnknownOutputParams; } | { pathname: `/Notification`; params?: Router.UnknownOutputParams; } | { pathname: `/Play`; params?: Router.UnknownOutputParams; } | { pathname: `/Premuim`; params?: Router.UnknownOutputParams; } | { pathname: `/Signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/Account/forgetpassword`; params?: Router.UnknownOutputParams; } | { pathname: `/Account/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/Account/request`; params?: Router.UnknownOutputParams; } | { pathname: `/Account/Signup`; params?: Router.UnknownOutputParams; } | { pathname: `/Account/User`; params?: Router.UnknownOutputParams; } | { pathname: `/UserStorage/profilePic`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/Advertise${`?${string}` | `#${string}` | ''}` | `/AutoDetection${`?${string}` | `#${string}` | ''}` | `/FileDetection${`?${string}` | `#${string}` | ''}` | `/ForgotPassword${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `/LinkDetection${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `/Menu${`?${string}` | `#${string}` | ''}` | `/Notification${`?${string}` | `#${string}` | ''}` | `/Play${`?${string}` | `#${string}` | ''}` | `/Premuim${`?${string}` | `#${string}` | ''}` | `/Signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/Account/forgetpassword${`?${string}` | `#${string}` | ''}` | `/Account/Login${`?${string}` | `#${string}` | ''}` | `/Account/request${`?${string}` | `#${string}` | ''}` | `/Account/Signup${`?${string}` | `#${string}` | ''}` | `/Account/User${`?${string}` | `#${string}` | ''}` | `/UserStorage/profilePic${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Advertise`; params?: Router.UnknownInputParams; } | { pathname: `/AutoDetection`; params?: Router.UnknownInputParams; } | { pathname: `/FileDetection`; params?: Router.UnknownInputParams; } | { pathname: `/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/LinkDetection`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/Menu`; params?: Router.UnknownInputParams; } | { pathname: `/Notification`; params?: Router.UnknownInputParams; } | { pathname: `/Play`; params?: Router.UnknownInputParams; } | { pathname: `/Premuim`; params?: Router.UnknownInputParams; } | { pathname: `/Signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Account/forgetpassword`; params?: Router.UnknownInputParams; } | { pathname: `/Account/Login`; params?: Router.UnknownInputParams; } | { pathname: `/Account/request`; params?: Router.UnknownInputParams; } | { pathname: `/Account/Signup`; params?: Router.UnknownInputParams; } | { pathname: `/Account/User`; params?: Router.UnknownInputParams; } | { pathname: `/UserStorage/profilePic`; params?: Router.UnknownInputParams; };
    }
  }
}
